# Generated by Django 4.1.5 on 2023-02-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=50)),
                ('user_address1', models.CharField(max_length=50)),
                ('user_address2', models.CharField(max_length=50)),
                ('user_city', models.CharField(max_length=50)),
                ('user_state', models.IntegerField(default=0)),
                ('user_zip', models.CharField(max_length=300)),
            ],
        ),
    ]
