# Generated by Django 4.1.5 on 2023-02-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_user_detail_user_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='orders',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='user_zip',
            field=models.IntegerField(),
        ),
    ]
