# Generated by Django 4.1.5 on 2023-02-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_user_detail_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='quantity',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='orders',
            field=models.CharField(default='', max_length=50),
        ),
    ]
