# Generated by Django 4.1.5 on 2023-02-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_user_detail_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='orders',
            field=models.CharField(max_length=50),
        ),
    ]
