# Generated by Django 4.1.5 on 2023-02-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_user_detail_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='orders',
            field=models.CharField(default='', max_length=50),
        ),
    ]
