# Generated by Django 4.1.5 on 2023-02-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_user_detail_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='order',
            field=models.JSONField(default='{}'),
        ),
    ]
