# Generated by Django 4.1.5 on 2023-02-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_product_quant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quant',
            field=models.IntegerField(default=1),
        ),
    ]
