# Generated by Django 4.1.5 on 2023-02-21 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_product_quant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quant',
        ),
    ]
