# Generated by Django 4.1.5 on 2023-02-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_product_quant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='order_history',
            field=models.JSONField(default=dict),
        ),
    ]
