# Generated by Django 4.1.5 on 2023-02-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_order_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='order_history',
            field=models.JSONField(default=dict),
        ),
    ]
