# Generated by Django 4.1.5 on 2023-02-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_remove_user_detail_order_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='order_history',
            field=models.CharField(default='', max_length=50),
        ),
    ]
