# Generated by Django 4.1.5 on 2023-02-26 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_user_detail_order_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_detail',
            name='order',
        ),
        migrations.RemoveField(
            model_name='user_detail',
            name='order_history',
        ),
    ]
