# Generated by Django 4.1.5 on 2023-02-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_user_detail_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='order',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user_detail',
            name='order_history',
            field=models.JSONField(default=dict),
        ),
    ]
