# Generated by Django 4.1.5 on 2023-02-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_user_detail_user_address1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_detail',
            name='user_address2',
        ),
        migrations.AddField(
            model_name='user_detail',
            name='order_buynow',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user_detail',
            name='quant_buynow',
            field=models.IntegerField(default=1),
        ),
    ]
