# Generated by Django 4.1.5 on 2023-03-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_product_actual_price_product_feature1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_detail',
            name='order',
        ),
        migrations.RemoveField(
            model_name='user_detail',
            name='order_history',
        ),
    ]
