# Generated by Django 4.1.5 on 2023-03-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_user_detail_order_user_detail_order_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='smallimage',
            field=models.ImageField(default='', upload_to='images/product'),
        ),
    ]
